### ISSUE TITLE
Suggested password.

### ISSUE THREAD

**Issue by virtadpt** [tarahmarie/nerdlist#26]
CPE1704TKS

**Comment by tarahmarie** [comment]
Interesting. Why?

**Comment by virtadpt** [comment]
It's the missile launch code from _Wargames_.

**Comment by tarahmarie** [comment]
That is awesome. Submit PR? I will absolutely approve.

**Comment by tarahmarie** [comment]
I believe you added really great passwords. Thank you! I will close this issue now. If you have other issues, please raise them; good discussion.
