### ISSUE TITLE
Alphabetical ordering?

### ISSUE THREAD

**Issue by MisterGlass** [tarahmarie/nerdlist#6]
As the list gets longer it will be harder for people to look for passwords the want to contribute, should possibly consider alphabetizing the list.

**Comment by tarahmarie** [comment]
Absolutely. I'll note that there are several potentially offensive passwords, and I've chosen to push those to the bottom. Likely, it makes sense to simply add a disclaimer at the top and change how I've ordered these to be totally alphabetical....until there's some data about how often they work, and then there'll be a reason to order by frequency of usage.

**Comment by koronkowy** [comment]
How are you going to handle password variations that use numbers in space of letters (eg. leetspeak)?

Would something like 0wned go under 'O' or '0'?

It seems like there would be value in nesting either way, intended alphabet character vs. numeric living together.

**Comment by tarahmarie** [comment]
How would one nest these without adding additional characters? I will likely strip the top comments soon to decrease iteration time through the list. Could a tab char be a single char instead of four spaces, etc?

**Comment by MisterGlass** [comment]
I would refrain from adding mutations (converting to l33t sp34k, adding in special chars at the end, etc) to the list, there are already tools out there that will automatically do those for you on a given wordlist.

Not sure what you asking about RE tab chars, I don't see any in the list.

**Comment by mc2squared** [comment]
I've got a PR incoming that sorts everything alphabetically - l33t permutations aren't the worst thing in the world here, not like we're working off of microcontrollers where an extra ~30 lines of essentially the same thing will actually hinder things

**Comment by tarahmarie** [comment]
Maya's PR solved the alphabetical question; it's a good idea that helps people rapidly sort for their own ideas and add permutations. I'm going to declare this issue resolved.
